### ISSUE TITLE
Pembagian_Tugas

### ISSUE THREAD

**Issue by andikasembiring21** [andikasembiring21/Tugas_TKPI#3]
Pembagian tugas ada:
1. Definition Vue and how to work Vue?
2. Perkembangan Vue untuk masa depan?
3. Spesifikasi Vue di bandingkan Framwork lain?
4. Kelebihan dan Kekurangan Vue?

Pilih bagian mana yang mau kamu selesaikan?

**Comment by Jonatal** [comment]
Aku pilih Kelebihan dan kekurangan Vue

**Comment by yamolase** [comment]
Aku pilih nomor 1

**Comment by FaisalTonniro27** [comment]
Aku pilih perkembangan Vue untuk masa depan

**Comment by andikasembiring21** [comment]
Ok teman-teman untuk pembagian materi sudah selesai, 
1. Definition Vue and how to work Vue?                                                       (YamamoniLase)
2. Perkembangan Vue untuk masa depan?                                                   (FaisalTonniro)
3. Spesifikasi Vue di bandingkan Framwork lain?                                          (AndikaSembiring)
4. Kelebihan dan Kekurangan Vue?                                                               (JonatalBangunSitanggang)

                   ok saya harap Tugas ini akan lancar kedepannya, mohon bantuan dan partisipasinya di dalam kelompok
