### ISSUE TITLE
Pembagian materi

### ISSUE THREAD

**Issue by andikasembiring21** [andikasembiring21/Tugas_TKPI#4]
Ok guys saya akan memberikan materi-materi terkait topik yang kita pilih silahkan untuk mengambil bagian masing-masing.

* Definition Vue and how to work Vue? 

* Perkembangan Vue untuk masa depan?

* beberapa Libraries dan Framework vue?

* Kelebihan dan Kekurangan Vue?

**Comment by Jonatal** [comment]
Saya memilih bagian Kelebihan dan kekurangan Vue

**Comment by FaisalTonniro27** [comment]
Saya memilih materi mengenai perkembangan Vue untuk masa depan

**Comment by yamolase** [comment]
Saya memilih bagian Definition Vue and how to work Vue

**Comment by andikasembiring21** [comment]
ok semua sudah memilih dan saya akan mengambil 1 yang tersisa. 
Berikut daftar pembagian lengkap nya:

1) Definition Vue and how to work Vue?           (Yamamoni Lase)

2) Perkembangan Vue untuk masa depan?       (Faisal Tonniro)

3) beberapa Libraries dan Framework vue?       (Andika Sembiring)

4) Kelebihan dan Kekurangan Vue?                   (Jonatal Bangun Sitanggang
