### ISSUE TITLE
Meet

### ISSUE THREAD

**Issue by andikasembiring21** [andikasembiring21/Tugas_TKPI#6]
kita akan meet di Ms.Team untuk, untuk jam akan kita sesuaikan dan untuk link meet akan saya bagikan di WA grup.
Terimakasih.

**Comment by Jonatal** [comment]
kita akan meet di Ms.Team untuk, untuk jam akan kita sesuaikan dan untuk link meet akan saya bagikan di WA grup.
Terimakasih. karna bermasalah, dialihkan lewat WA.

**Comment by andikasembiring21** [comment]
Hasil link meet:
https://mikroskilacid-my.sharepoint.com/:v:/g/personal/181113511_students_mikroskil_ac_id/EfctET6rFXhJppBrZVaybX8B1GNZn3-c2eQPuJaa-tE33A
