### ISSUE TITLE
Animasi and Create slide

### ISSUE THREAD

**Issue by andikasembiring21** [andikasembiring21/Tugas_TKPI#7]
Upload daftar Animasi yang akan di masukkan ke dalam slide kemudian create slide sesuai dengan animasi yang akan kalian kerjakan.

**Comment by yamolase** [comment]
Aku akan menambahkan Fragment Order pada  slide

**Comment by Jonatal** [comment]
Saya akan menambahan Fragments Order pada slide

**Comment by andikasembiring21** [comment]
saya menambahkan pop up di bagian animasi button
